// <auto-generated />
using System;
using DiagramAPI.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DiagramAPI.Migrations
{
    [DbContext(typeof(DiagramAPIContext))]
    partial class DiagramAPIContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024");

            modelBuilder.Entity("DiagramAPI.Models.Classifier", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<long?>("DiagramID");

                    b.Property<string>("Name");

                    b.Property<int>("Type");

                    b.HasKey("ID");

                    b.HasIndex("DiagramID");

                    b.ToTable("Classifiers");
                });

            modelBuilder.Entity("DiagramAPI.Models.Diagram", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.HasKey("ID");

                    b.ToTable("Diagrams");
                });

            modelBuilder.Entity("DiagramAPI.Models.Relationship", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<long?>("ClassifierID");

                    b.Property<int>("Type");

                    b.HasKey("ID");

                    b.HasIndex("ClassifierID");

                    b.ToTable("Relationships");
                });

            modelBuilder.Entity("DiagramAPI.Models.Classifier", b =>
                {
                    b.HasOne("DiagramAPI.Models.Diagram", "Diagram")
                        .WithMany("Classifiers")
                        .HasForeignKey("DiagramID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("DiagramAPI.Models.Relationship", b =>
                {
                    b.HasOne("DiagramAPI.Models.Classifier", "Classifier")
                        .WithMany("Relationships")
                        .HasForeignKey("ClassifierID");
                });
#pragma warning restore 612, 618
        }
    }
}
